# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-ast
        files: "(server/src.*)|(server/tests.*)"
      - id: trailing-whitespace
        files: "(server/.*)|(server/tests.*)"

  - repo: local
    hooks:
      - id: ruff-format
        name: Format with Ruff
        entry: poetry run ruff format
        language: system
        pass_filenames: false
        always_run: true

      - id: ruff-check
        name: Check with Ruff
        entry: poetry run ruff check . --fix
        language: system
        pass_filenames: false
        always_run: true

      - id: mypy
        name: Validate types with MyPy
        entry: poetry run mypy
        language: system
        types: [python]
        pass_filenames: false
        args: ["."]
